# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, -20, 1920, 1110))
        self.stackedWidget.setObjectName("stackedWidget")
        self.sleep = QtWidgets.QWidget()
        self.sleep.setObjectName("sleep")
        self.wakeButton = QtWidgets.QPushButton(self.sleep)
        self.wakeButton.setStyleSheet("QPushButton {background-color: #000000; color: white; font-size: 80px;}")
        self.wakeButton.setGeometry(QtCore.QRect(0, 0, 1920, 1110))
        self.wakeButton.setObjectName("wakeButton")
        self.stackedWidget.addWidget(self.sleep)
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.distanceTest = QtWidgets.QLabel(self.home)
        self.distanceTest.setGeometry(QtCore.QRect(1250, 760, 141, 31))
        self.distanceTest.setObjectName("distanceTest")
        self.backup_time_lbl = QtWidgets.QLabel(self.home)
        self.backup_time_lbl.setGeometry(QtCore.QRect(5, 1055, 300, 31))
        self.backup_time_lbl.setObjectName("back up timer")
        self.connection_status_label = QtWidgets.QLabel(self.home)
        self.connection_status_label.setGeometry(QtCore.QRect(5, 1070, 300, 31))
        self.connection_status_label.setObjectName("status label")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.home)
        self.calendarWidget.setGeometry(QtCore.QRect(731, 20, 1181, 681))
        self.calendarWidget.setObjectName("calendarWidget")
        self.scheduleBtn = QtWidgets.QPushButton(self.home)
        self.scheduleBtn.setGeometry(QtCore.QRect(730, 720, 491, 341))
        self.scheduleBtn.setObjectName("scheduleBtn")
        self.defectsBtn = QtWidgets.QPushButton(self.home)
        self.defectsBtn.setGeometry(QtCore.QRect(1420, 720, 491, 341))
        self.defectsBtn.setObjectName("defectsBtn")
        self.lblCapacity_home = QtWidgets.QLabel(self.home)
        self.lblCapacity_home.setGeometry(QtCore.QRect(1250, 740, 141, 31))
        self.lblCapacity_home.setObjectName("lblCapacity_home")
        self.lblTemperature_home = QtWidgets.QLabel(self.home)
        self.lblTemperature_home.setGeometry(QtCore.QRect(1250, 930, 141, 31))
        self.lblTemperature_home.setObjectName("lblTemperature_home")
        self.listView = QtWidgets.QListView(self.home)
        self.listView.setGeometry(QtCore.QRect(0, 20, 701, 1041))
        self.listView.setObjectName("listView")
        self.stackedWidget.addWidget(self.home)
        self.schedule = QtWidgets.QWidget()
        self.schedule.setObjectName("schedule")
        self.generate = QtWidgets.QPushButton(self.schedule)
        self.generate.setGeometry(QtCore.QRect(730, 720, 491, 341))
        self.generate.setObjectName("generate")
        self.scheduleQr = QtWidgets.QLabel(self.schedule)
        self.scheduleQr.setGeometry(QtCore.QRect(1600, 340, 500, 500))
        self.scheduleQr.setObjectName("scheduleQr")
        self.scheduleBack = QtWidgets.QPushButton(self.schedule)
        self.scheduleBack.setGeometry(QtCore.QRect(1420, 720, 491, 341))
        self.scheduleBack.setObjectName("scheduleBack")
        self.lblCapacity = QtWidgets.QLabel(self.schedule)
        self.lblCapacity.setGeometry(QtCore.QRect(1250, 740, 141, 41))
        self.lblCapacity.setObjectName("lblCapacity")
        self.lblTemperature = QtWidgets.QLabel(self.schedule)
        self.lblTemperature.setGeometry(QtCore.QRect(1250, 930, 131, 41))
        self.lblTemperature.setObjectName("lblTemperature")

        self.calendarWidgetSchedule = QtWidgets.QCalendarWidget(self.schedule)
        self.calendarWidgetSchedule.setGeometry(QtCore.QRect(731, 20, 800, 681))
        self.calendarWidgetSchedule.setObjectName("calendarWidget")

        self.lblSlots = QtWidgets.QLabel(self.schedule)
        self.lblSlots.setGeometry(QtCore.QRect(1680, 10, 300, 140))
        self.lblSlots.setObjectName("lblSlots")
        self.lcdSlots = QtWidgets.QLCDNumber(self.schedule)
        self.lcdSlots.setGeometry(QtCore.QRect(1575, 100, 300, 140))
        self.lcdSlots.setObjectName("lcdSlots")
        self.slotRight = QtWidgets.QPushButton(self.schedule)
        self.slotRight.setGeometry(QtCore.QRect(1730, 300, 131, 171))
        self.slotRight.setObjectName("slotRight")
        self.slotLeft = QtWidgets.QPushButton(self.schedule)
        self.slotLeft.setGeometry(QtCore.QRect(1600, 300, 131, 171))
        self.slotLeft.setObjectName("slotLeft")
        self.radioButtonGroup = QtWidgets.QButtonGroup()
        self.slot1 = QtWidgets.QRadioButton(self.schedule)
        self.slot1.setGeometry(QtCore.QRect(20, 40, 561, 50))
        self.slot1.setObjectName("slot1")
        self.slot1.setStyleSheet("QRadioButton::indicator { width: 50px; height: 50px;}")
        self.slot1.setChecked(True)
        self.slot2 = QtWidgets.QRadioButton(self.schedule)
        self.slot2.setGeometry(QtCore.QRect(20, 100, 561, 50))
        self.slot2.setObjectName("slot2")
        self.slot2.setStyleSheet("QRadioButton::indicator { width: 50px; height: 50px;}")
        self.slot3 = QtWidgets.QRadioButton(self.schedule)
        self.slot3.setGeometry(QtCore.QRect(20, 160, 561, 50))
        self.slot3.setObjectName("slot3")
        self.slot3.setStyleSheet("QRadioButton::indicator { width: 50px; height: 50px;}")
        self.slot4 = QtWidgets.QRadioButton(self.schedule)
        self.slot4.setGeometry(QtCore.QRect(20, 220, 561, 50))
        self.slot4.setObjectName("slot4")
        self.slot4.setStyleSheet("QRadioButton::indicator { width: 50px; height: 50px;}")
        self.slot5 = QtWidgets.QRadioButton(self.schedule)
        self.slot5.setGeometry(QtCore.QRect(20, 280, 561, 50))
        self.slot5.setObjectName("slot5")
        self.slot5.setStyleSheet("QRadioButton::indicator { width: 50px; height: 50px;}")
        self.slot6 = QtWidgets.QRadioButton(self.schedule)
        self.slot6.setGeometry(QtCore.QRect(20, 340, 561, 50))
        self.slot6.setObjectName("slot6")
        self.slot6.setStyleSheet("QRadioButton::indicator { width: 50px; height: 50px;}")
        self.slot7 = QtWidgets.QRadioButton(self.schedule)
        self.slot7.setGeometry(QtCore.QRect(20, 400, 561, 50))
        self.slot7.setObjectName("slot7")
        self.slot7.setStyleSheet("QRadioButton::indicator { width: 50px; height: 50px;}")
        self.slot8 = QtWidgets.QRadioButton(self.schedule)
        self.slot8.setGeometry(QtCore.QRect(20, 460, 561, 50))
        self.slot8.setObjectName("slot8")
        self.slot8.setStyleSheet("QRadioButton::indicator { width: 50px; height: 50px;}")
        self.slot9 = QtWidgets.QRadioButton(self.schedule)
        self.slot9.setGeometry(QtCore.QRect(20, 520, 561, 50))
        self.slot9.setObjectName("slot9")
        self.slot9.setStyleSheet("QRadioButton::indicator { width: 50px; height: 50px;}")
        self.slot10 = QtWidgets.QRadioButton(self.schedule)
        self.slot10.setGeometry(QtCore.QRect(20, 580, 561, 50))
        self.slot10.setObjectName("slot10")
        self.slot10.setStyleSheet("QRadioButton::indicator { width: 50px; height: 50px;}")
        self.slot11 = QtWidgets.QRadioButton(self.schedule)
        self.slot11.setGeometry(QtCore.QRect(20, 640, 561, 50))
        self.slot11.setObjectName("slot11")
        self.slot11.setStyleSheet("QRadioButton::indicator { width: 50px; height: 50px;}")
        self.slot12 = QtWidgets.QRadioButton(self.schedule)
        self.slot12.setGeometry(QtCore.QRect(20, 700, 561, 50))
        self.slot12.setObjectName("slot12")
        self.slot12.setStyleSheet("QRadioButton::indicator { width: 50px; height: 50px;}")
        self.slot13 = QtWidgets.QRadioButton(self.schedule)
        self.slot13.setGeometry(QtCore.QRect(20, 760, 561, 50))
        self.slot13.setObjectName("slot13")
        self.slot13.setStyleSheet("QRadioButton::indicator { width: 50px; height: 50px;}")
        self.slot14 = QtWidgets.QRadioButton(self.schedule)
        self.slot14.setGeometry(QtCore.QRect(20, 820, 561, 50))
        self.slot14.setObjectName("slot14")
        self.slot14.setStyleSheet("QRadioButton::indicator { width: 50px; height: 50px;}")
        self.slot15 = QtWidgets.QRadioButton(self.schedule)
        self.slot15.setGeometry(QtCore.QRect(20, 880, 561, 50))
        self.slot15.setStyleSheet("QRadioButton::indicator { width: 50px; height: 50px;}")
        self.slot15.setObjectName("slot15")
        self.radioButtonGroup.addButton(self.slot1,1)
        self.radioButtonGroup.addButton(self.slot2,2)
        self.radioButtonGroup.addButton(self.slot3,3)
        self.radioButtonGroup.addButton(self.slot4,4)
        self.radioButtonGroup.addButton(self.slot5,5)
        self.radioButtonGroup.addButton(self.slot6,6)
        self.radioButtonGroup.addButton(self.slot7,7)
        self.radioButtonGroup.addButton(self.slot8,8)
        self.radioButtonGroup.addButton(self.slot9,9)
        self.radioButtonGroup.addButton(self.slot10,10)
        self.radioButtonGroup.addButton(self.slot11,11)
        self.radioButtonGroup.addButton(self.slot12,12)
        self.radioButtonGroup.addButton(self.slot13,13)
        self.radioButtonGroup.addButton(self.slot14,14)
        self.radioButtonGroup.addButton(self.slot15,15)

        self.stackedWidget.addWidget(self.schedule)
        self.defect = QtWidgets.QWidget()
        self.defect.setObjectName("defect")
        self.defectQr = QtWidgets.QLabel(self.defect)
        self.defectQr.setGeometry(QtCore.QRect(1200, 340, 500, 500))
        self.defectQr.setObjectName("defectQr")
        self.defectBack = QtWidgets.QPushButton(self.defect)
        self.defectBack.setGeometry(QtCore.QRect(1420, 720, 491, 341))
        self.defectBack.setObjectName("defectBack")
        self.defectTypeBox = QtWidgets.QComboBox(self.defect)
        self.defectTypeBox.setGeometry(QtCore.QRect(760, 70, 600, 201))
        self.defectTypeBox.setObjectName("defectTypeBox")
        self.generateDefect = QtWidgets.QPushButton(self.defect)
        self.generateDefect.setGeometry(QtCore.QRect(730, 720, 491, 341))
        self.generateDefect.setObjectName("generateDefect")
        self.defectListView = QtWidgets.QListView(self.defect)
        self.defectListView.setGeometry(QtCore.QRect(0, 20, 701, 1041))
        self.defectListView.setObjectName("defectList")
        self.stackedWidget.addWidget(self.defect)
        MainWindow.setCentralWidget(self.centralwidget)

        self.setupScreen = QtWidgets.QWidget()
        self.setupScreen.setObjectName("home")
        self.roomNumTbox = QtWidgets.QLineEdit(self.setupScreen)
        self.roomNumTbox.setGeometry(QtCore.QRect(1250, 760, 141, 31))
        self.roomNumTbox.setObjectName("distanceTest")
        self.savebtn = QtWidgets.QPushButton(self.setupScreen)
        self.savebtn.setGeometry(QtCore.QRect(730, 720, 491, 341))
        self.savebtn.setObjectName("scheduleBtn")
        self.stackedWidget.addWidget(self.setupScreen)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.scheduleQr.setText(_translate("MainWindow", "QR Placeholder"))
        self.defectQr.setText(_translate("MainWindow", "QR Placeholder"))
        self.wakeButton.setText(_translate("MainWindow", ""))
        self.distanceTest.setText(_translate("MainWindow", "Distance test"))
        self.scheduleBtn.setText(_translate("MainWindow", "Schedule"))
        self.defectsBtn.setText(_translate("MainWindow", "Defects"))
        self.lblSlots.setText(_translate("MainWindow", "Slots"))
        self.lblCapacity_home.setText(_translate("MainWindow", "Capacity Placeholder"))
        self.lblTemperature_home.setText(_translate("MainWindow", "Temperature Placeholder"))
        self.generate.setText(_translate("MainWindow", "Generate"))
        self.scheduleBack.setText(_translate("MainWindow", "Back"))
        self.lblCapacity.setText(_translate("MainWindow", "Capacity Placeholder"))
        self.lblTemperature.setText(_translate("MainWindow", "Temperature Placeholder"))
        # self.lblDay.setText(_translate("MainWindow", "Day"))
        # self.lblMonth.setText(_translate("MainWindow", "Month"))
        # self.dayLeft.setText(_translate("MainWindow", "<"))
        # self.monthLeft.setText(_translate("MainWindow", "<"))
        self.slotLeft.setText(_translate("MainWindow", "<"))
        # self.dayRight.setText(_translate("MainWindow", ">"))
        # self.monthRight.setText(_translate("MainWindow", ">"))
        self.slotRight.setText(_translate("MainWindow", ">"))
        self.roomNumTbox.setText(_translate("MainWindow", "Set Room Number"))
        self.savebtn.setText(_translate("MainWindow", "Save"))
        self.slot1.setText(_translate("MainWindow", "Timeslot 1 08:30 09:20"))
        self.slot2.setText(_translate("MainWindow", "Timeslot 2 09:20 10:10"))
        self.slot3.setText(_translate("MainWindow", "Timeslot 3 10:30 11:20"))
        self.slot4.setText(_translate("MainWindow", "Timeslot 4 11:20 12:10"))
        self.slot5.setText(_translate("MainWindow", "Timeslot 5 12:10 13:00"))
        self.slot6.setText(_translate("MainWindow", "Timeslot 6 13:00 13:50"))
        self.slot7.setText(_translate("MainWindow", "Timeslot 7 13:50 14:40"))
        self.slot8.setText(_translate("MainWindow", "Timeslot 8 15:00 15:50"))
        self.slot9.setText(_translate("MainWindow", "Timeslot 9 15:50 16:40"))
        self.slot10.setText(_translate("MainWindow", "Timeslot 10 17:00 17:50"))
        self.slot11.setText(_translate("MainWindow", "Timeslot 11 17:50 18:40"))
        self.slot12.setText(_translate("MainWindow", "Timeslot 12 18:40 19:30"))
        self.slot13.setText(_translate("MainWindow", "Timeslot 13 19:30 20:20"))
        self.slot14.setText(_translate("MainWindow", "Timeslot 14 20:20 21:10"))
        self.slot15.setText(_translate("MainWindow", "Timeslot 15 21:10 22:00"))
        self.defectBack.setText(_translate("MainWindow", "Back"))
        self.generateDefect.setText(_translate("MainWindow", "Generate"))

