# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ScheduleScreen.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(720, 640, 461, 401))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1450, 640, 461, 401))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1200, 650, 231, 121))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1200, 880, 231, 121))
        self.label_2.setObjectName("label_2")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 711, 1041))
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setRowCount(15)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(690)
        self.tableWidget.setColumnWidth(0, 50)
        self.tableWidget.setColumnWidth(1, 640)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(68)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(800, 20, 971, 141))
        self.comboBox.setObjectName("comboBox")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1180, 230, 261, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(630, 10, 51, 51))
        self.checkBox.setObjectName("checkBox")
        self.checkBox.setStyleSheet("QCheckBox::indicator { width: 60px; height: 60px;}")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(630, 75, 51, 51))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_2.setStyleSheet("QCheckBox::indicator { width: 60px; height: 60px;}")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(630, 140, 51, 51))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_3.setStyleSheet("QCheckBox::indicator { width: 60px; height: 60px;}")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(630, 210, 51, 51))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_4.setStyleSheet("QCheckBox::indicator { width: 60px; height: 60px;}")
        self.checkBox_5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(630, 275, 51, 51))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_5.setStyleSheet("QCheckBox::indicator { width: 60px; height: 60px;}")
        self.checkBox_6 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_6.setGeometry(QtCore.QRect(630, 340, 51, 51))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_6.setStyleSheet("QCheckBox::indicator { width: 60px; height: 60px;}")
        self.checkBox_7 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_7.setGeometry(QtCore.QRect(630, 410, 51, 51))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_7.setStyleSheet("QCheckBox::indicator { width: 60px; height: 60px;}")
        self.checkBox_8 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_8.setGeometry(QtCore.QRect(630, 480, 51, 51))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_8.setStyleSheet("QCheckBox::indicator { width: 60px; height: 60px;}")
        self.checkBox_9 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_9.setGeometry(QtCore.QRect(630, 550, 51, 51))
        self.checkBox_9.setObjectName("checkBox_9")
        self.checkBox_9.setStyleSheet("QCheckBox::indicator { width: 60px; height: 60px;}")
        self.checkBox_10 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_10.setGeometry(QtCore.QRect(630, 620, 51, 51))
        self.checkBox_10.setObjectName("checkBox_10")
        self.checkBox_10.setStyleSheet("QCheckBox::indicator { width: 60px; height: 60px;}")
        self.checkBox_11 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_11.setGeometry(QtCore.QRect(630, 690, 51, 51))
        self.checkBox_11.setObjectName("checkBox_11")
        self.checkBox_11.setStyleSheet("QCheckBox::indicator { width: 60px; height: 60px;}")
        self.checkBox_12 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_12.setGeometry(QtCore.QRect(630, 760, 51, 51))
        self.checkBox_12.setObjectName("checkBox_12")
        self.checkBox_12.setStyleSheet("QCheckBox::indicator { width: 60px; height: 60px;}")
        self.checkBox_13 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_13.setGeometry(QtCore.QRect(630, 830, 51, 51))
        self.checkBox_13.setObjectName("checkBox_13")
        self.checkBox_13.setStyleSheet("QCheckBox::indicator { width: 60px; height: 60px;}")
        self.checkBox_14 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_14.setGeometry(QtCore.QRect(630, 895, 51, 51))
        self.checkBox_14.setObjectName("checkBox_14")
        self.checkBox_14.setStyleSheet("QCheckBox::indicator { width: 60px; height: 60px;}")
        self.checkBox_15 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_15.setGeometry(QtCore.QRect(630, 960, 51, 51))
        self.checkBox_15.setObjectName("checkBox_15")
        self.checkBox_15.setStyleSheet("QCheckBox::indicator { width: 60px; height: 60px;}")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(810, 230, 171, 81))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(1450, 230, 171, 81))
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Generate"))
        self.pushButton_2.setText(_translate("MainWindow", "Back"))
        self.label.setText(_translate("MainWindow", "capacity"))
        self.label_2.setText(_translate("MainWindow", "temp"))
        self.label_3.setText(_translate("MainWindow", "Month"))
        self.pushButton_3.setText(_translate("MainWindow", "<-"))
        self.pushButton_4.setText(_translate("MainWindow", "->"))

